
# SECRETS THAT SHOULD NEVER BE STORED ANYWHERE PEOPLE CAN SEE THEM !!!

export APP_KEY="A_RANDOM_STRING"

export CLIENT_ID="YOUR_YELP_CLIENT_ID"
export YELP_API_KEY="YOUR_YELP_API_KEY (THE REALLY LONG STRING!)"